### ISSUE TITLE
Unity Error in Soldier Convo.cs

### ISSUE THREAD

**Issue by castana1962** [akeller/Unity-AI-AR#1]
Hello Mrs Keller
I am trying your GitHub Unity Project and I get the following error

Assets/SoldierConvo.cs(170,19): error CS0123: A method or delegate `SoldierConvo.OnSpeechInput(IBM.Watson.DeveloperCloud.Services.SpeechToText.v1.SpeechRecognitionEvent)' parameters do not match delegate `IBM.Watson.DeveloperCloud.Services.SpeechToText.v1.SpeechToText.OnRecognize(IBM.Watson.DeveloperCloud.Services.SpeechToText.v1.SpeechRecognitionEvent, System.Collections.Generic.Dictionary<string,object>)' parameters

For it, Could you help me to fix it?
Thanks for your time
Alejandro Castan

**Comment by akeller** [comment]
Hi there - I have not had time to update this repo since the major breaking changes introduced by the SDK since I wrote it. I recommend looking at the SDK examples themselves. I hope to get some time in the future to update.

**Comment by akeller** [comment]
Here is a similar file with Assistant + STT + TTS which should work with the SDK, although I have not check it since it was updated last week: https://gist.github.com/akeller/5d01bf62c401fe1c5a9d279c7da0c475

**Comment by castana1962** [comment]
Hi Amara, please do not worry, I will try with another AR examples..... Thanks anyway !!!!

**Comment by akeller** [comment]
Code is updated!
