### ISSUE TITLE
How add the Watson Machine Learning service to Unity?

### ISSUE THREAD

**Issue by castana1962** [akeller/Unity-AI-AR#5]
Hi Amara
Sorry to bother you but I need to add the Watson Machine Learning service to my AR/VR projects in Unity but since that unfortunate this service is not included in the Watson SDK for Unity at the moment. I know that I can do it by the  UnityWebRequest Class but I do not how to do it, Could you help me with that?
Thanks for your time
Alejandro

**Comment by akeller** [comment]
I'm not sure Watson ML is available outside of Watson Studio at this time, but I'm checking with a coworker. Here's the docs I found for Watson ML: https://console.bluemix.net/docs/#services/PredictiveModeling/index.html

**Comment by akeller** [comment]
Here is better documentation: https://dataplatform.cloud.ibm.com/docs/content/analyze-data/pm_service_api_spark_online.html?context=analytics&linkInPage=true

Depending on what you do, you'll need to parse the response you get back.

**Comment by castana1962** [comment]
Hi Amara,
First of all, thanks for your help.
On the other hand and since I am making Educational Games/Apps with Unity and Watson and like I am learning all about Watson, I am a little lost in my mind....
I was in the IBM Cloud Event in Argentina a few days ago and the IBM employee are very nice but It is a new topic and it is very hard for me to include Machine Learning in the Watson SDK for Unity without help..
One more time, thanks for your help and your patience
Sincerely
Alejandro

**Comment by castana1962** [comment]
Sorry  but I forget to tell you that since Machine Learning is not included in the Watson SDK for Unity for some technical questions but I could do it by UnityWebRequest Class , for it, I would have to create a new C# Class with it to have access to Machine Learning. If you have any idea about how create it, please let me know. Thanks

**Comment by akeller** [comment]
I recommend you look at Unity's scripting docs on UnityWebRequest. https://docs.unity3d.com/ScriptReference/Networking.UnityWebRequest.html

There are a number of different ways to work with the returned response JSON, one of which I have documented on my blog. https://medium.com/@MissAmaraKay/parsing-json-in-c-unity-573d1e339b6f

**Comment by castana1962** [comment]
Hi again
I am learning about this topic and sometimes it is very hard for me to learn...
Thanks for your patience and help !!!
Regards
Alejandro

**Comment by castana1962** [comment]
Hi Amara.
Sorry to bother you but I tried to use the ARC according to your post here

https://medium.com/@MissAmaraKay/parsing-json-in-c-unity-573d1e339b6f

After I added the Endpoint and header name and header value like said your example and then, the ARC asked me my Watson Assistant Username and Password and I adde them and I got the following( please see the picture) 404 NOT FOUND. Maybe I am making a mistake, for it, Could you help me to fix this? Thanks for your time
![arcscreen1](https://user-images.githubusercontent.com/13416817/44785388-8eb32b80-ab45-11e8-9d24-ac1198be92ef.jpg)
![arcscreen2](https://user-images.githubusercontent.com/13416817/44785399-94107600-ab45-11e8-9635-08face2cf5f4.jpg)

**Comment by akeller** [comment]
You need to use the username and password for your assistant service, not your IBM Cloud account. Read more here: https://www.ibm.com/watson/developercloud/assistant/api/v1/curl.html?curl#authentication

**Comment by akeller** [comment]
Closing this issue.

If you have questions about IBM products please join the wdc community Slack: http://wdc-slack-inviter.mybluemix.net/

I also invite you to check out [IBM Developer](https://developer.ibm.com/ ) and ask questions [here](https://developer.ibm.com/answers/) where more people monitor incoming questions.

**Comment by castana1962** [comment]
Hi Amara
Thanks for your help !!!
